name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x', '14.x', '16.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Setup Intl
        uses: sarisia/setup-icu@v1
        id: setup-icu
        with:
          noexport: true

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        uses: sarisia/action-uses-icu-function@v2
        env:
          NODE_ICU_DATA: ${{ steps.setup-icu.outputs.icu-data-dir }}
        run: yarn lint

      - name: Test
        uses: sarisia/action-uses-icu-function@v2
        env:
          NODE_ICU_DATA: ${{ steps.setup-icu.outputs.icu-data-dir }}
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build
